FROM php:8.2-fpm

# Set working directory
WORKDIR /usr/src/app

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install php extensions
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions mbstring pdo_pgsql zip exif pcntl gd memcached opcache sockets && \
    docker-php-ext-install bcmath

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    unzip \
    git \
    curl \
    lua-zlib-dev \
    libmemcached-dev \
    supervisor

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -

RUN apt-get install -y nodejs

RUN curl -L https://www.npmjs.com/install.sh | sh

RUN pecl install swoole \
    && docker-php-ext-enable swoole

RUN mkdir /usr/local/bin -p

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && mv composer /usr/local/bin/composer

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Add user for laravel application
#RUN groupadd www
#RUN useradd -ms /bin/bash -g www www


COPY ./docker/php/php.ini /usr/local/etc/php/conf.d/app.ini
COPY ./docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

#copy composer.json and composer.lock
COPY --chown=$uid:$uid ./laravel/composer.* ./

# Deployment steps
RUN composer install --prefer-dist --no-dev --no-interaction --no-autoloader --no-scripts

COPY --chown=$uid:$uid ./laravel ./

# add root to www group
# RUN chmod -R 777 /usr/src/app/storage

RUN composer dump-autoload --optimize

RUN PATH=$PATH:/usr/src/app/vendor/bin:bin

RUN mkdir -p "/etc/supervisor/logs"

COPY --chown=$uid:$uid ./docker/php/supervisord.conf /etc/supervisor/supervisord.conf

RUN chmod -Rf 777 /usr/src/app/storage

CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
